**NumPy**

What is NumPy?

NumPy stands for Numerical Python. NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project is freely available.

Why to use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

**How to create an array?**

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.zeros(2)

In [5]:
b

array([0., 0.])

In [6]:
c = np.ones(3)

In [7]:
c

array([1., 1., 1.])

In [8]:
x = np.ones(10)

In [9]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# create an empty array with 2 elements
e = np.empty(3)

In [11]:
e

array([1., 1., 1.])

In [12]:
z = np.empty(3)
z

array([1., 1., 1.])

In [13]:
z = np.empty(2)

In [14]:
z

array([0., 0.])

In [15]:
z = np.empty(3)

In [16]:
z

array([1., 1., 1.])

In [17]:
# with range of elements
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# defined range with intervals
f = np.arange(3,21,3)
f

array([ 3,  6,  9, 12, 15, 18])

In [19]:
# linearly spaced arrays
g = np.linspace(0,20, num=5)

In [20]:
g

array([ 0.,  5., 10., 15., 20.])

**1D Array**

In [21]:
import numpy as np
a = np.array([3,4,5,6,7])

In [22]:
a

array([3, 4, 5, 6, 7])

In [23]:
type(a)

numpy.ndarray

**2D Array**

In [24]:
b = np.array([[5, 5, 5], [5, 6, 7], [2, 4, 6]])

In [25]:
b

array([[5, 5, 5],
       [5, 6, 7],
       [2, 4, 6]])

**Vector:** An array with a single dimension (there is no difference between row and column vectors).

**Matrix:** Refers to an array with two dimensions.

In [26]:
import numpy as np
a = np.array([5, 5, 5,])

In [27]:
a

array([5, 5, 5])

In [28]:
type(a)

numpy.ndarray

In [29]:
len(a)

3

In [30]:
a[0]

5

In [31]:
a[1]

5

In [32]:
a[0:3]

array([5, 5, 5])

In [33]:
a[0:]

array([5, 5, 5])

The NumPy **ndarray** class is used to represent both matrices and vectors

**3D or higher**

*For 3-D or higher dimensional arrays, the term tensor is used.*

In [34]:
# Create an empty array with 2 elements
q = np.empty(3)

In [35]:
q

array([1., 1., 1.])

In [36]:
# specific data types in array
i = np.ones(5, dtype=np.int8) 

In [37]:
i

array([1, 1, 1, 1, 1], dtype=int8)

In [38]:
j = np.ones(3,dtype=np.float64)

In [39]:
j

array([1., 1., 1.])

**How to create 2-D arrays?**

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [42]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**How to create a 3-D array?**

In [43]:
c = np.arange(24).reshape(2,3,4)

In [44]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])