## NumPy Practice Session

In [1]:
import numpy as np

**Creating an array using NumPy**

In [6]:
# 1-D array
food = np.array(["Pakora", "Samosa", "Raita", "Biryani"])

In [7]:
food

array(['Pakora', 'Samosa', 'Raita', 'Biryani'], dtype='<U7')

In [8]:
price = np.array([50, 50, 20, 120])

In [9]:
price

array([ 50,  50,  20, 120])

In [10]:
type(food)

numpy.ndarray

In [11]:
type(price)

numpy.ndarray

In [12]:
len(price)

4

In [13]:
len(food)

4

In [14]:
# indexing
price[3]

120

In [15]:
food[3]

'Biryani'

In [23]:
food.ndim

1

In [24]:
price.ndim

1

In [26]:
price.mean()

60.0

**Methods**

In [32]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [34]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [30]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [51]:
np.ones(5, dtype='int8')

array([1, 1, 1, 1, 1], dtype=int8)

In [31]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [52]:
np.empty(0)

array([], dtype=float64)

In [67]:
np.empty(9)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 7.45050994e-321, 1.07372987e-311, 1.07372987e-311,
       2.56765117e-312])

In [69]:
np.zeros(20, dtype='int8')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [76]:
np.empty([2,3], dtype='float64')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# specify
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
# with a specific interval
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [85]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [87]:
# line space
np.linspace(1, 100, num=10, dtype='int8')

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100], dtype=int8)

In [88]:
# line space
np.linspace(1, 100, num=10) # float output is by default

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [91]:
# specify your data type
np.ones(50, dtype='int8')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int8)

In [92]:
np.ones(50, dtype='float64')

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Array functions

**numpy.sort:** 

In [96]:
a = np.array([2, 30, 1, 0.5, 12, 11, 3.14, 1.5, 100, 200, 150, 12])

In [97]:
a.sort()

In [98]:
a

array([  0.5 ,   1.  ,   1.5 ,   2.  ,   3.14,  11.  ,  12.  ,  12.  ,
        30.  , 100.  , 150.  , 200.  ])

In [99]:
b=np.array([10.2, 3.4, 53.6, 91.6, 45.5])

In [100]:
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [109]:
c=np.concatenate((a,b))

In [110]:
c.sort()

In [111]:
c

array([  0.5 ,   1.  ,   1.5 ,   2.  ,   3.14,   3.4 ,  10.2 ,  11.  ,
        12.  ,  12.  ,  30.  ,  45.5 ,  53.6 ,  91.6 , 100.  , 150.  ,
       200.  ])

### 2-D Arrays

In [142]:
d=np.array([[1,2,3], [3,4,5]])
d

array([[1, 2, 3],
       [3, 4, 5]])

In [143]:
d.ndim

2

**Concatenate 2-D arrays**

In [147]:
e = np.array([[12,13,14], [14,15,16]])

In [148]:
e

array([[12, 13, 14],
       [14, 15, 16]])

In [149]:
e.ndim

2

In [150]:
np.concatenate((d,e), axis=1)

array([[ 1,  2,  3, 12, 13, 14],
       [ 3,  4,  5, 14, 15, 16]])

In [151]:
np.concatenate((d,e), axis=0)

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [12, 13, 14],
       [14, 15, 16]])

### 3-D Arrays

In [155]:
a = np.array([[[1,2], 
           [2,3]],
         [[11,12],
          [12,13]],
         [[21,22],
         [22,23]]])

In [156]:
a

array([[[ 1,  2],
        [ 2,  3]],

       [[11, 12],
        [12, 13]],

       [[21, 22],
        [22, 23]]])

In [170]:
b = np.array([[[101,102], [103,104]],
          
         [[111,112], [113,114]],
          
         [[121,122], [123,124]]])

In [171]:
b

array([[[101, 102],
        [103, 104]],

       [[111, 112],
        [113, 114]],

       [[121, 122],
        [123, 124]]])

In [172]:
a.ndim

3

In [173]:
b.ndim

3

In [178]:
c = np.concatenate((a,b), axis=0)
c

array([[[  1,   2],
        [  2,   3]],

       [[ 11,  12],
        [ 12,  13]],

       [[ 21,  22],
        [ 22,  23]],

       [[101, 102],
        [103, 104]],

       [[111, 112],
        [113, 114]],

       [[121, 122],
        [123, 124]]])

In [180]:
d=np.concatenate((a,b), axis=1)
d

array([[[  1,   2],
        [  2,   3],
        [101, 102],
        [103, 104]],

       [[ 11,  12],
        [ 12,  13],
        [111, 112],
        [113, 114]],

       [[ 21,  22],
        [ 22,  23],
        [121, 122],
        [123, 124]]])

In [182]:
e=np.concatenate((a,b), axis=2)
e

array([[[  1,   2, 101, 102],
        [  2,   3, 103, 104]],

       [[ 11,  12, 111, 112],
        [ 12,  13, 113, 114]],

       [[ 21,  22, 121, 122],
        [ 22,  23, 123, 124]]])

In [183]:
# to find the number of dimensions
a.ndim

3

In [184]:
b.ndim

3

In [185]:
c.ndim

3

In [186]:
d.ndim

3

In [187]:
e.ndim

3

In [188]:
# size (number of elements)
a.size

12

In [189]:
b.size

12

In [191]:
c.size

24

In [192]:
d.size

24

In [193]:
d.size

24

In [194]:
a

array([[[ 1,  2],
        [ 2,  3]],

       [[11, 12],
        [12, 13]],

       [[21, 22],
        [22, 23]]])

In [195]:
# shape
a.shape

(3, 2, 2)

In [196]:
b

array([[[101, 102],
        [103, 104]],

       [[111, 112],
        [113, 114]],

       [[121, 122],
        [123, 124]]])

In [197]:
b.shape

(3, 2, 2)

In [199]:
c

array([[[  1,   2],
        [  2,   3]],

       [[ 11,  12],
        [ 12,  13]],

       [[ 21,  22],
        [ 22,  23]],

       [[101, 102],
        [103, 104]],

       [[111, 112],
        [113, 114]],

       [[121, 122],
        [123, 124]]])

In [198]:
c.shape

(6, 2, 2)

In [206]:
f=np.arange(1,21)

In [207]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [209]:
# reshape
f.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [211]:
# reshape rows into columns
f.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [216]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [223]:
# reshape, convert 1D into 2D
g=np.reshape(f, newshape=(1,20), order='C')
g

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [224]:
# convert 1D into 2D
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [225]:
f.ndim

1

In [226]:
g.ndim

2

In [231]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [232]:
f.ndim

1

In [246]:
# row wise 2D conversion
g = f[np.newaxis, :]

In [247]:
g

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [248]:
g.ndim

2

In [249]:
# column wise 2D conversion
h = f[:, np.newaxis]

In [250]:
h

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [251]:
h.ndim

2

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [6]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7,8]])

In [18]:
x.ndim

2

In [19]:
y.ndim

2

In [20]:
z = np.array([5, 6]) # 1D array

In [21]:
z.ndim

1

In [22]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Shape and size of an array

- This section covers *ndarray.ndim, ndarray.size, ndarray.shape*

- **ndarray.ndim** will tell you the number of axes, or dimensions, of the array.

- **ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

- **ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [29]:
a1 = np.array([[[0, 1, 2, 3], 
                [4, 5, 6, 7]],

               [[0, 1, 2, 3],
                [4, 5, 6, 7]],

               [[0 ,1 ,2, 3],
                [4, 5, 6, 7]]])

In [30]:
a1.ndim

3

In [31]:
a1.size # number of elements

24

In [32]:
a1.shape 

(3, 2, 4)

### Reshaping an Array

- arr.reshape() - Using arr.reshape() will give a new shape to an array without changing the data.

In [34]:
a = np.arange(6)

In [35]:
a

array([0, 1, 2, 3, 4, 5])

In [36]:
a.ndim

1

In [37]:
a.shape

(6,)

In [38]:
a.size

6

In [47]:
# the intended output array must have the same numbe of elements as the original array
a1 = a.reshape(2,3) # to reshape array into 2 rows and 3 columns
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
a1.ndim

2

In [49]:
a1.size

6

In [50]:
a1.shape

(2, 3)

In [51]:
a2 = a.reshape(3,2) # to reshape array into 3 rows and 2 columns
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
a2.shape

(3, 2)

In [53]:
a2.ndim

2

With **np.reshape**, we can specify a few optional parameters:

In [56]:
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
# for example:
a2=np.reshape(a2, newshape=(2, 3), order='C')
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
a2=np.reshape(a2, newshape=(1,6), order='C')
a2

array([[0, 1, 2, 3, 4, 5]])